// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZB4BjwWlbTyWYv91DuaOsEVzU9nXQV6M',
    appId: '1:42331170991:web:56390366a082a37e728c5a',
    messagingSenderId: '42331170991',
    projectId: 'news-1bd27',
    authDomain: 'news-1bd27.firebaseapp.com',
    storageBucket: 'news-1bd27.appspot.com',
    measurementId: 'G-RSRS4BJFQ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9BQjdBd2gwMskQfJN_13pb1DVSdqUnKQ',
    appId: '1:42331170991:android:daba6762ec3a7f44728c5a',
    messagingSenderId: '42331170991',
    projectId: 'news-1bd27',
    storageBucket: 'news-1bd27.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzylhMopFRwEron1G_zZogUKf1u5tP7-0',
    appId: '1:42331170991:ios:51b7c19bba3645e0728c5a',
    messagingSenderId: '42331170991',
    projectId: 'news-1bd27',
    storageBucket: 'news-1bd27.appspot.com',
    iosClientId:
        '42331170991-52nj7f3mdon5hs02q5c0qt4p3ompsm61.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzylhMopFRwEron1G_zZogUKf1u5tP7-0',
    appId: '1:42331170991:ios:51b7c19bba3645e0728c5a',
    messagingSenderId: '42331170991',
    projectId: 'news-1bd27',
    storageBucket: 'news-1bd27.appspot.com',
    iosClientId:
        '42331170991-52nj7f3mdon5hs02q5c0qt4p3ompsm61.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsApp',
  );
}
